rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: true #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 200      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key

###################  项目启动端口  ###################
server:
  port: 6080

###################  spring配置  ###################
spring:
  profiles:
    active: dev

#####################################################################
########################  swagger2 开启开关  ##########################
#####################################################################
swagger:
  enable: true # 是否开启 swagger 调试  true 开启，false 关闭

#####################################################################
########################  特殊校验开启开关  ##########################
#####################################################################
specialValidator:
  enable: true # 是否开启 特殊校验 调试  true 开启，false 关闭

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:cn/whs/jwt/modules/dao/mappings/*.xml
  typeAliasesPackage: cn.whs.jwt.modules.entity
  global-config:
    id-type: 0  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?serverTimezone=UTC
    username: root
    password: 666
    db-name: spring_boot
    filters: log4j,wall,mergeStat
    redis:
        host: 127.0.0.1
        #password: redispassword
        port: 6379
        pool:
          max-idle: 100
          min-idle: 1
          max-active: 1000
          max-wait: -1

#####################################################################
########################  写入日志  ##########################
#####################################################################

logging:
  level.root: info
  level.cn.whs.jwt: debug
  file: G:/mylog/spring-boot.log


