###################  项目启动端口  ###################
server:
  port: 8080

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    view:
      prefix: /templates





