###################  spring配置  ###################
spring:
  profiles:
    active: dev

---
#####################################################################
########################  开发环境profile  ##########################
#####################################################################
server:
  port: 88

spring:
  profiles: dev

