###################  项目启动端口  ###################
server:
  port: 6090
###################  spring配置  ###################
spring:
  profiles:
    active: dev
###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:cn/whs/db/modules/dao/mappings/*.xml
  typeAliasesPackage: cn.whs.db.modules.entity
  global-config:
    id-type: 0  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

---

#####################################################################
########################  多数据源 开启开关  ##########################
#####################################################################
dynamicSwitch:
  multi-datasource-open: true #是否开启多数据源(true/false)

multi-datasource:
  dataSourceBizOne:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_biz_one?serverTimezone=Asia/Shanghai
    username: root
    password: 666
  dataSourceBizTwo:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_biz_two?serverTimezone=Asia/Shanghai
    username: root
    password: 666

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_core?serverTimezone=Asia/Shanghai
    username: root
    password: 666
    db-name: spring_boot_core
    filters: log4j,wall,mergeStat
  data:
      mongodb:
        uri: mongodb://whs:pwd66@localhost:27017/spring_boot

#####################################################################
########################  写入日志  ##########################
#####################################################################
logging:
  level.root: info
  level.cn.whs.db: debug
  file: G:/mylog/spring-boot.log


