
server:
  port: 6080

###################  spring配置  ###################
spring:
  profiles:
    active: dev


# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.whs.mybatis.modules.entity

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: 666

#####################################################################
########################  写入日志 打印sql ##########################
#####################################################################

logging:
  level.root: info
  level.com.whs.mybatis.modules.dao: debug
  file: G:/mylog/spring-boot.log


